const person = {
    firstname: 'saikat',
    lastname: 'saha',
    get fullname(){
        return `${person.firstname} ${person.lastname}`
    },
    set fullname(value){
        //if(typeof value !== 'string') return;

        if(typeof value !== 'string')
            throw new Error('Value is not a string');

        const parts = value.split(' ');
        if(parts.length !== 2)
            throw new Error('Enter a first and last name');
        this.firstname = parts[0];
        this.lastname = parts[1];
    }
};

try {
    person.fullname = null;
}
catch (e) {
    alert(e);
}

person.fullname = null; //setter
person.fullname; //getter

const e = new Error(); //Error
throw e; //exception


lines after throw statement will not get executed and jump out of method control will move to catch block